name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  install-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13']
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install uv
        run: |
          pip install uv

      - name: Create and activate venv, install llm and plugin
        run: |
          python -m venv .venv
          source .venv/bin/activate
          uv pip install --upgrade pip
          uv pip install llm
          uv pip install -e .
          uv pip list

      - name: Check llm CLI version
        run: |
          source .venv/bin/activate
          llm --version

      - name: Check llm plugin is installed
        run: |
          source .venv/bin/activate
          llm plugins | grep llm-fragments-rust

      - name: Run a basic llm command
        run: |
          source .venv/bin/activate
          llm --help